# Generated by Django 5.1.6 on 2025-02-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='search_date_time',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='filter_fuel_type',
            new_name='fuel_type',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='search_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='filter_price_range',
            new_name='price_range',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='filter_transmission_type',
            new_name='transmission_type',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='search_vehicle_type',
            new_name='vehicle_type',
        ),
    ]
