# Generated by Django 5.1.6 on 2025-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_search_date_time_vehicle_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='paymentStatus',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='location',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Successful', 'Successful'), ('Failed', 'Failed')], max_length=50, null=True),
        ),
    ]
