# Generated by Django 5.1.6 on 2025-02-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_remove_booking_paymentstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
    ]
